name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Project
    runs-on: macos-12
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_13.3.app
      
    - name: Build and test macOS
      run: xcodebuild clean test -project MovieDB/MovieDB.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Build and test iOS
      run: xcodebuild clean test -project MovieDB/MovieDB.xcodeproj -scheme "CI_iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.4,name=iPhone 13" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

    - name: Build and test app
      run: xcodebuild clean test -workspace MovieDBApp/MovieDBApp.xcworkspace -scheme "MovieDBApp" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.4,name=iPhone 13" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
