name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      
    - name: Build and test
      run: xcodebuild clean test -project MovieDB/MovieDB.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO